# Generated by Django 4.1 on 2022-09-03 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField()),
                ('website_name', models.CharField(max_length=30)),
                ('website_image', models.ImageField(upload_to='website/images')),
                ('website_username', models.CharField(max_length=200)),
                ('website_password', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_website_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
