# Generated by Django 4.1 on 2022-09-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesdata',
            name='website_image',
            field=models.ImageField(blank=True, null=True, upload_to='website/images'),
        ),
        migrations.AlterField(
            model_name='websitesdata',
            name='website_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='websitesdata',
            name='website_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='websitesdata',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websitesdata',
            name='website_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
