# Generated by Django 4.1 on 2022-09-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_alter_websitesdata_website_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesdata',
            name='website_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
