# Generated by Django 4.1 on 2022-09-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_websitesdata_website_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesdata',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('only_me', 'Only Me')], default='only_me', max_length=30),
        ),
    ]
